"""
Created on Thu Aug 16 14:00:49 2018

@script: text spitter for transliteration corpus (character seperated)

@author: Moodser Hussain
@contact: fa17-rcs-005@ciitlahore.edu.pk
@org: COMSATS University Islamabad, Lahore Campus, Pakistan
"""

#####################################
## Special Thanks to 
#### Dr. Rao Muhammad Adeel Nawab
#### Sir Muhammad Sharjeel
#####################################

"""
@libraries

"""
import sys
import os

"""
@input

provide output file generated by the 'wikipedia title extrator script' 
(https://github.com/clab/wikipedia-parallel-titles)
as an input to this python script
"""
inputFile = sys.argv[1]
    
#######################################
## Saving the text of both languages in different files
## Text of both languages is seperated by '|' in each line
#######################################
print ('Performing Step 01/03')
lang01 = open('lang01.tmp', 'a+')
lang02 = open('lang02.tmp', 'a+')
with open(inputFile, 'r') as data:
    for line in data:
        check = 0
        for ch in line:
            if ch=='|':
                check=1
            elif check==0:
                lang01.write(ch)
            elif check==1:
                lang02.write(ch)
            else:
                print()
        lang01.write('\n')
lang01.close()
lang02.close()        
print ('Step 01/03 Completed Successfully')
print ('#################################')

#######################################
## Removing pre and post spaces from each line
#######################################
print ('Performing Step 02/03')
lang01text = open('lang01.tmp2', 'a+')
lang02text = open('lang02.tmp2', 'a+')

with open("lang01.tmp") as lines:
    for line in lines:
        lang01text.write(line.strip())
        lang01text.write('\n')
        
with open("lang02.tmp") as lines:
    for line in lines:
        lang02text.write(line.strip())
        lang02text.write('\n')
lang01text.close()
lang02text.close()
print ('Step 02/03 Completed Successfully')
print ('#################################')        
#######################################
## converting words in space seperated characters
## and handling duplicate spaces
## to train the transliteration model in MOSES
#######################################
lang01final = open('lang01.txt', 'a+')
lang02final = open('lang02.txt', 'a+')
print ('Performing Step 03/03')
with open("lang01.tmp2") as lines:
    for line in lines:
        for ch in line:
            if ch==' ':
                lang01final.write('')
            elif ch=='\n':
                lang01final.write('\n')
            else:
                lang01final.write(ch+' ')

with open("lang02.tmp2") as lines:
    for line in lines:
        for ch in line:
            if ch==' ':
                lang02final.write('')
            elif ch=='\n':
                lang02final.write('\n')
            else:
                lang02final.write(ch+' ')
lang01final.close()
lang02final.close() 
print ('Step 03/03 Completed Successfully')
print ('#################################')                
#######################################
## Deleting extra/temporary files generated during preprocessing
#######################################
print ('Generating Output Files')
print ('#################################')
os.remove('lang01.tmp')
os.remove('lang01.tmp2')
os.remove('lang02.tmp')
os.remove('lang02.tmp2')
print ('::: SUCCESS :::')
print ('#################################')
#######################################
## End of Script - Splitter
#######################################